extends Node2D

export(Array, PackedScene) var flier_waves
export(Array, PackedScene) var gem_waves
export(Array, PackedScene) var skull_waves
export(PackedScene) var boss_wave
export(PackedScene) var gem

var boss

var current_position := -1

onready var play_area = $PlayArea
onready var positions := $Positions

# 6 7 8 popcorn left
# 9 10 11 popcorn right

func _ready():
	Globals.connect_game()
	Globals.reset_game()
	Globals.bgm.play("March")
	sequence()


func sequence():
	yield(get_tree().create_timer(1.2), "timeout")
	spawn(flier_waves[9])
	yield(get_tree().create_timer(1.5), "timeout")
	spawn(flier_waves[10])
	yield(get_tree().create_timer(1.5), "timeout")
	spawn(flier_waves[11])
	yield(get_tree().create_timer(3.0), "timeout")
	spawn(flier_waves[6])
	yield(get_tree().create_timer(1.5), "timeout")
	spawn(flier_waves[7])
	yield(get_tree().create_timer(1.5), "timeout")
	spawn(flier_waves[8])
	yield(get_tree().create_timer(1.1), "timeout")
	spawn(flier_waves[9])
	spawn(flier_waves[10])
	spawn(flier_waves[11])
	yield(get_tree().create_timer(1.0), "timeout")
	spawn(flier_waves[6])
	spawn(flier_waves[7])
	spawn(flier_waves[8])
	yield(get_tree().create_timer(0.9), "timeout")
	spawn(flier_waves[9])
	spawn(flier_waves[10])
	spawn(flier_waves[11])
	yield(get_tree().create_timer(0.8), "timeout")
	spawn(flier_waves[6])
	spawn(flier_waves[7])
	spawn(flier_waves[8])
	play_area.tween_radius(40)
	yield(get_tree().create_timer(0.4), "timeout")
	spawn(flier_waves[5])
	yield(get_tree().create_timer(0.4), "timeout")
	spawn(flier_waves[4])
	yield(get_tree().create_timer(1.2), "timeout")
	spawn(flier_waves[2])
	yield(get_tree().create_timer(2.0), "timeout")
	spawn(skull_waves[3])
	spawn(flier_waves[6])
	yield(get_tree().create_timer(1.2), "timeout")
	spawn(flier_waves[0])
	yield(get_tree().create_timer(1.5), "timeout")
	spawn(skull_waves[3])
	yield(get_tree().create_timer(1.2), "timeout")
	spawn(flier_waves[1])
	yield(get_tree().create_timer(1.5), "timeout")
	spawn(skull_waves[1])
	yield(get_tree().create_timer(1.2), "timeout")
	spawn(flier_waves[2])
	yield(get_tree().create_timer(1.5), "timeout")
	spawn(skull_waves[2])
	yield(get_tree().create_timer(1.2), "timeout")
	spawn(flier_waves[3])
	yield(get_tree().create_timer(1.5), "timeout")
	spawn(skull_waves[1])
	yield(get_tree().create_timer(1.2), "timeout")
	spawn(flier_waves[0])
	yield(get_tree().create_timer(1.5), "timeout")
	spawn(skull_waves[1])
	yield(get_tree().create_timer(2.0), "timeout")
	spawn(flier_waves[0])
	play_area.tween_radius(64)
	yield(get_tree().create_timer(0.6), "timeout")
	spawn(flier_waves[6])
	yield(get_tree().create_timer(0.6), "timeout")
	spawn(flier_waves[7])
	yield(get_tree().create_timer(0.6), "timeout")
	spawn(flier_waves[8])
	yield(get_tree().create_timer(0.6), "timeout")
	spawn(flier_waves[9])
	yield(get_tree().create_timer(0.6), "timeout")
	spawn(flier_waves[10])
	yield(get_tree().create_timer(0.6), "timeout")
	spawn(flier_waves[11])
	yield(get_tree().create_timer(3.0), "timeout")
	spawn(gem_waves[2])
	yield(get_tree().create_timer(0.6), "timeout")
	spawn(flier_waves[6])
	yield(get_tree().create_timer(0.6), "timeout")
	spawn(flier_waves[7])
	yield(get_tree().create_timer(0.6), "timeout")
	spawn(flier_waves[8])
	yield(get_tree().create_timer(0.6), "timeout")
	spawn(flier_waves[9])
	yield(get_tree().create_timer(0.6), "timeout")
	spawn(flier_waves[10])
	yield(get_tree().create_timer(0.6), "timeout")
	spawn(flier_waves[11])
	yield(get_tree().create_timer(2.0), "timeout")
	spawn(gem_waves[1])
	yield(get_tree().create_timer(2.0), "timeout")
	spawn(flier_waves[0])
	yield(get_tree().create_timer(1.2), "timeout")
	spawn(flier_waves[1])
	yield(get_tree().create_timer(1.2), "timeout")
	spawn(flier_waves[2])
	yield(get_tree().create_timer(1.2), "timeout")
	spawn(flier_waves[3])
	yield(get_tree().create_timer(2.0), "timeout")
	spawn(skull_waves[0])
	yield(get_tree().create_timer(2.0), "timeout")
	spawn(flier_waves[0])
	yield(get_tree().create_timer(1.2), "timeout")
	spawn(flier_waves[1])
	spawn(skull_waves[1])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(flier_waves[2])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(flier_waves[3])
	yield(get_tree().create_timer(3.0), "timeout")
	spawn(skull_waves[0])
	yield(get_tree().create_timer(2.0), "timeout")
	spawn(flier_waves[0])
	spawn(skull_waves[1])
	yield(get_tree().create_timer(1.2), "timeout")
	spawn(flier_waves[1])
	yield(get_tree().create_timer(1.2), "timeout")
	spawn(flier_waves[2])
	play_area.tween_radius(32)
	spawn(skull_waves[2])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(gem_waves[2])
	yield(get_tree().create_timer(3.0), "timeout")
	spawn(skull_waves[1])
	spawn(flier_waves[0])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(skull_waves[2])
	spawn(flier_waves[1])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(skull_waves[1])
	spawn(flier_waves[2])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(skull_waves[2])
	spawn(flier_waves[3])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(skull_waves[0])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(skull_waves[1])
	spawn(flier_waves[0])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(skull_waves[2])
	spawn(flier_waves[1])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(skull_waves[1])
	spawn(flier_waves[2])
	play_area.tween_radius(24)
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(skull_waves[2])
	spawn(flier_waves[3])
	yield(get_tree().create_timer(2.5), "timeout")
	spawn(flier_waves[3])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(flier_waves[0])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(flier_waves[1])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(flier_waves[2])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(flier_waves[3])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(skull_waves[0])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(flier_waves[0])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(flier_waves[1])
	spawn(skull_waves[1])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(flier_waves[2])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(flier_waves[3])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(skull_waves[0])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(flier_waves[0])
	spawn(skull_waves[1])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(flier_waves[1])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(flier_waves[2])
	spawn(skull_waves[2])
	play_area.tween_radius(12)
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(flier_waves[3])
	yield(get_tree().create_timer(2.2), "timeout")
	spawn(flier_waves[0])
	yield(get_tree().create_timer(4.0), "timeout")
	boss_sequence()
	

func boss_sequence():
	Globals.boss_phase = true
	play_area.tween_radius(12)
	yield(get_tree().create_timer(8.0), "timeout")
	boss = boss_wave.instance()
	add_child(boss)
	boss_repeat()
	

func boss_repeat():
	yield(get_tree().create_timer(2.5), "timeout")
	if Globals.boss_defeated:
		return
	spawn(flier_waves[0])
	yield(get_tree().create_timer(2.5), "timeout")
	if Globals.boss_defeated:
		return
	spawn(flier_waves[1])
	boss_teleport()
	yield(get_tree().create_timer(2.5), "timeout")
	if Globals.boss_defeated:
		return
	spawn(flier_waves[2])
	yield(get_tree().create_timer(2.5), "timeout")
	if Globals.boss_defeated:
		return
	spawn(flier_waves[3])
	boss_teleport()
	boss_repeat()
	
	
func boss_teleport():
	Globals.sfx.play("Teleport")
	var spawn = gem.instance()
	spawn.position = boss.global_position
	add_child(spawn)
	current_position += 1
	if current_position >= positions.get_child_count():
		current_position = 0
	boss.global_position = positions.get_child(current_position).global_position
	
	
func victory_sequence():
	play_area.visible = false
	get_tree().call_group("Enemies", "queue_free")
	Globals.sfx.play("Hurt")
	Globals.bgm.stop("March")
	Globals.particles.create_explosion(boss.global_position, 160)
	Globals.particles.create_explosion(boss.global_position, 140)
	Globals.particles.create_explosion(boss.global_position, 120)
	Globals.particles.create_explosion(boss.global_position, 100)
	Globals.particles.create_explosion(boss.global_position, 80)
	Globals.particles.create_explosion(boss.global_position, 60)
	Globals.particles.create_explosion(boss.global_position, 40)
	Globals.particles.create_explosion(boss.global_position, 20)
	Globals.hit_stop.stop(2.0)
	Globals.sfx.play("Victory")
	Bullets.unmount($BulletsEnvironment)
	yield(get_tree().create_timer(5.0), "timeout")
	get_tree().change_scene("res://scenes/GameOver.tscn")

	
	
func spawn(scene):
	var wave = scene.instance()
	add_child(wave)
